{% set name = "fastsrm" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastsrm-{{ version }}.tar.gz
  sha256: a3b53d9eaea5d313fab49f8043bf144d2c74daabeb1d3de254a9949bbeb8ff09

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - joblib
    - matplotlib-base
    - python >={{ python_min }}
    - python-picard
    - scikit-learn
    - tqdm
    - numpy >=1.12
    - scikit-learn >=0.23
    - python-picard
    - tqdm


test:
  imports:
    - fastsrm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hugorichard/FastSRM
  summary: Fast Shared response model
  license: MIT
  license_file: ./LICENSE

extra:
  recipe-maintainers:
    - hugorichard
