{% set name = "fastsrm" %}
{% set version = "0.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastsrm-{{ version }}.tar.gz
  sha256: ca50d7222fd8328ace3c616084c2e1aa7e25668ec6b2fcbcc46567e5b81ec01d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - joblib >=1.1.0
    - matplotlib-base >=2.0.0
    - python >={{ python_min }}
    - numpy >=1.12
    - scikit-learn >=0.23
    - pytest >=6.2.5
    - scipy >=0.18.0


test:
  imports:
    - fastsrm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hugorichard/FastSRM
  summary: Fast Shared response model
  license: MIT
  license_file: ./LICENSE

extra:
  recipe-maintainers:
    - hoechenberger
    - hugorichard
